//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOWERVIEW
    {
        public int FLOWER_ID { get; set; }
        public string FLOWER_NAME { get; set; }
        public int CHAR_ID { get; set; }
        public string CHAR_DESC { get; set; }
        public int COLOR_ID { get; set; }
        public string COLOR_NAME { get; set; }
        public Nullable<int> FLOWER_PRICE { get; set; }
        public string FLOWER_SIZE { get; set; }
    }
}
