//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asp9Entities : DbContext
    {
        public asp9Entities()
            : base("name=asp9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHARACTERISTIC> CHARACTERISTICs { get; set; }
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<FLOWER> FLOWERs { get; set; }
        public virtual DbSet<FLOWERVIEW> FLOWERVIEWs { get; set; }
    }
}
